// <auto-generated />
using System;
using Laldy_MaquihaCostes_RossignolTravelAgency.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Laldy_MaquihaCostes_RossignolTravelAgency.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231115134331_travelAndTravelers")]
    partial class travelAndTravelers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCapital")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PointsOfInterest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationID");

                    b.ToTable("AllEvents");
                });

            modelBuilder.Entity("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Travel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TravelerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("TravelerID");

                    b.ToTable("Travels");
                });

            modelBuilder.Entity("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Traveler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Travelers");
                });

            modelBuilder.Entity("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Destination", b =>
                {
                    b.HasOne("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Events", b =>
                {
                    b.HasOne("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Destination", null)
                        .WithMany("EventsList")
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Travel", b =>
                {
                    b.HasOne("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Destination", "Destination")
                        .WithMany("TravelList")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Traveler", null)
                        .WithMany("TravelList")
                        .HasForeignKey("TravelerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Destination", b =>
                {
                    b.Navigation("EventsList");

                    b.Navigation("TravelList");
                });

            modelBuilder.Entity("Laldy_MaquihaCostes_RossignolTravelAgency.Data.Models.Traveler", b =>
                {
                    b.Navigation("TravelList");
                });
#pragma warning restore 612, 618
        }
    }
}
